# Generated by Django 4.0.5 on 2022-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaCoderApp', '0002_rename_familia_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
